

- id: alpinestars
  link: https://www.sportpursuit.com/catalog/product/view/id/1358113?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Alpinestars%24s-NoCat%24loc-A%24x-UK_email7_product%24p-21&utm_source=partnership
  image: P..alpinestars.jpg
  content:
    - title: Alpinestars
      style: sm
    - paragraph: -50%
      style: price
      color: "#FA8C38"

- id: oakley
  link: https://www.sportpursuit.com/catalog/product/view/id/2058690?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Oakley%24s-NoCat%24loc-A%24x-UK_email7_product%24p-22&utm_source=partnership
  image: P..oakley.jpg
  content:
    - title: Oakley
      style: sm
    - paragraph: -53%
      style: price
      color: "#FA8C38"

- id: vivobarefoot
  link: https://www.sportpursuit.com/catalog/product/view/id/2026740?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Vivobarefoot%24s-NoCat%24loc-A%24x-UK_email7_product%24p-23&utm_source=partnership
  image: P..vivobarefoot.jpg
  content:
    - title: Vivobarefoot
      style: sm
    - paragraph: -54%
      style: price
      color: "#FA8C38"

- id: aqualung
  link: https://www.sportpursuit.com/catalog/product/view/id/2091434?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Aqualung%24s-NoCat%24loc-A%24x-UK_email7_product%24p-21&utm_source=partnership
  image: P..aqualung.jpg
  content:
    - title: Aqualung
      style: sm
    - paragraph: -50%
      style: price
      color: "#FA8C38"

- id: asics
  link: https://www.sportpursuit.com/catalog/product/view/id/2018267?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Asics%24s-NoCat%24loc-A%24x-UK_email7_product%24p-22&utm_source=partnership
  image: P..asics.jpg
  content:
    - title: Asics
      style: sm
    - paragraph: -50%
      style: price
      color: "#FA8C38"

- id: garmin
  link: https://www.sportpursuit.com/catalog/product/view/id/2088190?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Garmin%24s-NoCat%24loc-A%24x-UK_email7_product%24p-23&utm_source=partnership
  image: P..garmin.jpg
  content:
    - title: Garmin
      style: sm
    - paragraph: -38%
      style: price
      color: "#FA8C38"

- id: zray
  link: https://www.sportpursuit.com/catalog/product/view/id/2081541?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Zray%24s-NoCat%24loc-A%24x-UK_email7_product%24p-24&utm_source=partnership
  image: P..zray.jpg
  content:
    - title: Zray
      style: sm
    - paragraph: -44%
      style: price
      color: "#FA8C38"

- id: aku
  link: https://www.sportpursuit.com/catalog/product/view/id/2090049?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-AKU%24s-NoCat%24loc-A%24x-UK_email7_product%24p-25&utm_source=partnership
  image: P..aku.jpg
  content:
    - title: AKU
      style: sm
    - paragraph: -50%
      style: price
      color: "#FA8C38"

- id: macaco
  link: https://www.sportpursuit.com/catalog/product/view/id/1913066?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Macaco%24s-NoCat%24loc-A%24x-UK_email7_product%24p-26&utm_source=partnership
  image: P..macaco.jpg
  content:
    - title: Macaco
      style: sm
    - paragraph: -50%
      style: price
      color: "#FA8C38"

- id: rapha
  link: https://www.sportpursuit.com/catalog/product/view/id/1826771?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Rapha%24s-NoCat%24loc-A%24x-UK_email7_product%24p-20&utm_source=partnership
  image: P..rapha.jpg
  content:
    - title: Rapha
      style: sm
    - paragraph: -50%
      style: price
      color: "#FA8C38"

- id: sigg
  link: https://www.sportpursuit.com/catalog/product/view/id/1857099?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Sigg%24s-NoCat%24loc-A%24x-UK_email7_product%24p-21&utm_source=partnership
  image: P..sigg.jpg
  content:
    - title: Sigg
      style: sm
    - paragraph: -48%
      style: price
      color: "#FA8C38"

- id: skiffo
  link: https://www.sportpursuit.com/catalog/product/view/id/1755280?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Skiffo%24s-NoCat%24loc-A%24x-UK_email7_product%24p-23&utm_source=partnership
  image: P..skiffo.jpg
  content:
    - title: Skiffo
      style: sm
    - paragraph: -45%
      style: price
      color: "#FA8C38"

- id: marmot
  link: https://www.sportpursuit.com/catalog/product/view/id/1896386?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Marmot%24s-NoCat%24loc-A%24x-UK_email7_product%24p-&utm_source=partnership
  image: P..marmot.jpg
  content:
    - title: Marmot
      style: sm
    - paragraph: -52%
      style: price
      color: "#FA8C38"

- id: inov8
  link: https://www.sportpursuit.com/catalog/product/view/id/2102096?st=Partnership&ad=SecretEscapes&campaign=t-Brand%24b-Inov8%24s-NoCat%24loc-A%24x-UK_email7_product%24p-&utm_source=partnership
  image: P..inov8.jpg
  content:
    - title: Inov8
      style: sm
    - paragraph: -40%
      style: price
      color: "#FA8C38"